# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  GitVersion.FullSemVer: ''

steps:
- checkout: self
  persistCredentials: true
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1.x SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    
- task: gitversion/setup@0
  displayName: 'Setup GitVersion'
  inputs:
    versionSpec: '5.2.x'
- task: gitversion/execute@0
  displayName: Use GitVersion
  inputs:
    updateAssemblyInfo: true
    updateAssemblyInfoFilename: $(Build.WorkingDirectory)/SpaceAPI.Host/AssemblyInfo.cs
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.FullSemVer'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    
- task: DotNetCoreCLI@2
  displayName: Publish project to $(Build.ArtifactStagingDirectory)
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Move to artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: 'Container'

- script: |
     git tag $(GitVersion.FullSemVer)
     git push origin $(GitVersion.FullSemVer)
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Add git tag $(GitVersion.FullSemVer)'

