# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1.x SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    
- task: gitversion/setup@0
  displayName: 'Setup GitVersion'
  inputs:
    versionSpec: '5.2.x'
- task: gitversion/execute@0
  displayName: Use GitVersion

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'ae104835-07d5-4d1e-a39c-14132e2e8544'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '/property:Version=$(fullSemVer)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    
- task: DotNetCoreCLI@2
  displayName: Publish project to $(Build.ArtifactStagingDirectory)
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Move to artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: 'Container'

- script: |
     git tag $(GitVersion.FullSemVer)
     git push origin $(GitVersion.FullSemVer)
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Add git tag $(GitVersion.FullSemVer)'

