// <auto-generated />
using System;
using BrixelAPI.SpaceState.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrixelAPI.SpaceState.Migrations
{
    [DbContext(typeof(SpaceStateContext))]
    [Migration("20200807202527_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrixelAPI.SpaceState.Domain.SpaceStateChangedAggregate.SpaceStateChangedLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChangedAtDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IsOpen", "ChangedAtDateTime", "ChangedByUser")
                        .IsUnique();

                    b.ToTable("SpaceStateChangedLog");
                });
#pragma warning restore 612, 618
        }
    }
}
