// <auto-generated />
namespace SpaceAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adds_statelogging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adds_statelogging));
        
        string IMigrationMetadata.Id
        {
            get { return "201508251844558_adds_statelogging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
