name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: .NET Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx
